# Generated by Django 2.2.11 on 2020-06-13 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='classes.Class')),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.School')),
                ('subject', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=120)),
                ('outline', models.IntegerField()),
                ('video_url', models.CharField(max_length=129)),
                ('thumbnail', models.ImageField(upload_to='lessons')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classes.Class')),
                ('subjects', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classes.Subject')),
            ],
        ),
    ]
