# Generated by Django 2.2.11 on 2020-06-13 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20200613_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolmanager',
            name='classes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classes.Class'),
        ),
        migrations.AlterField(
            model_name='schoolmanager',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Student'),
        ),
    ]
